{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/scripts/evaluate.py

Noticed a typo print message and that we weren't logging things correctly
* removed print
* `logging` -> `logger`
* Messages logged to correct module, not root

Fixed logging typos to in mlflow logger

---

cookiecutter.json

Changing CC to default to latest Orbyter image.
* cookiecutter.json default
* oob CC scaffolded repos will use Orbyter 2.0.
* Need to test image works. Will do so.

Changing default image ml-dev-2.0

---

{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name }}/util/logging.py

Make sure logging directories exist for info/error logs
* mkdir statements
* Containers that don't have `log` directory won't fail.

mkdir for logging files

---

{{ cookiecutter.repo_name }}/logging.yml

Changed default logging
* Root logging to INFO (blocks tons of debug messages from mlflow
* Only warn on `alembic`, used by sqlalchemy
* less cruft from logging

Changed default logging

---

{{ cookiecutter.repo_name }}/Makefile

Add a new command, `make ci-test-interactive`: it runs pytest, and if it sees any error, immediately stops and gives you an interactive ipdb session to facilitate debugging.
* New `make` command
* N/A
* Change is untested since I don't know how to add tests for the Makefile: I've been using something like this in another repo and it has worked so far.

Add interactive CI command to makefile

---

{{ cookiecutter.repo_name }}/{{ cookiecutter.repo_name.replace("-", "_") }}/util/logging.py

Fixes a f-string in logging.py to avoid flake8 violation code F541: "f-string without any placeholders". This was triggering CI build fails when using orbyter 3.0 docker images.
* Change f-string to standard string on line 88
* CI no longer fails for scaffolded repo when using orbyter 3.0 images.

Fixed f-string that triggered F541 flake8 violation code with python 3.8

---

{{ cookiecutter.repo_name }}/docsrc/index.rst

The headers don't match the Sphinx style guide right now (https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html). Essentially, it's starting with H3.
* Add an H1 at the top with the name of the project (recommended)
* Made the H3s->H2s
* Formatting a bit different
* Docs look good with this formatting.

Headers now match Sphinx style guide

---

{{ cookiecutter.repo_name }}/.github/workflows/ci.yml
{{ cookiecutter.repo_name }}/docker/action/README.md
{{ cookiecutter.repo_name }}/docker/action/action-exec.sh
{{ cookiecutter.repo_name }}/docker/action/action.yml

Previously, the default CI workflow tries running the tests on the base orbyter image, and assumes that there are no dependencies installed in the project Dockerfile. This forces everyone to update the CI workflow yaml file every time the Dockerfile is updated in order to have a consistent CI setup.
This fixes the problem by updating the github CI workflow to use a github action defined in the `docker/action` directory that uses the project Dockerfile to build the container for running CI.
* CI workflow invokes the github action defined in the `docker/action` directory
* Github action is defined in `docker/action/action.yml` file and the action documentation is in `docker/action/README.md`.
* Added bash script `docker/action/action-exec.sh` that acts as an entrypoint for container.
* CI …

fix(ci): changed github ci workflow to run ci in container defined by project dockerfile

---

cookiecutter.json

The title is the entire PR. Very simple. 
* Changed cookiecutter.json file to have 3.0 as default image.

Bumping orbyter ml-dev image to 3.0

---

cookiecutter.json
{{ cookiecutter.repo_name }}/.github/workflows/ci.yml

Moving to new 3.1 Orbyter ml-dev image as the default. 
* Change default image
* Changed name of action (from test -> ci)
Closes #31

Move to Orbyter 3.1 image

---

{{ cookiecutter.repo_name }}/Makefile

Test/lint make commands fail out of the box because they require `dev-start`. However, this is not listed as a requirement. I believe this was removed because someone was annoyed the about the docker images building every time. So, we have three options:
1. Keep as is. CON: inproper use of a Makefile. Requirements should be listed for all commands
2. Add `dev-start` requirement and always rebuild. CON: takes a bit more time as images need to build
3. Add `dev-start` and don't rebuild images in container is running.
This PR implements 3.
* Add `dev-start` requiremnt
* Don't rebuild images in containers are running

Spin up containers before running tests/lint

---

hooks/post_gen_project.sh
{{ cookiecutter.project_name }}/README.md

Ml-dev 3.2 image has been baked and pushed to Dockerhub so this PR updates `cookiecutter.json`. Since DVC was added to 3.2, this PR also contains commands in Makefile to initialize dvc repo and add a dvc remote which would be ran early in a project.

Moving to 3.2 image. Add dvc init and remote add commands to Makefile

---

{{ cookiecutter.project_name }}/Makefile
{{ cookiecutter.project_name }}/README.md

Linters don't change code, they only check that it obeys rules https://en.wikipedia.org/wiki/Lint_(software)
`black` and `isort` are code formatters (though black can also be used to lint, as it is in `ci-black`
* Add a new command `format` which is an alias of deprecated command `lint`

rename lint -> format

---

{{ cookiecutter.project_name }}/Makefile

`-t` allows tools like `pytest` to provide the same colorized terminal output that you'd get from within the container or on the host machine
* use `-t` 
* `make ci-test` will give colorized output
* this all works on my local for another project, but I'm not sure if `ci-_` is used in other use cases where somehow -t would bork it?

feat: allow colorized output for make commands

---

.github/workflows/ci.yml
README.md
{{ cookiecutter.project_name }}/{{ cookiecutter.package_name }}/scripts/train_test.py

The default tests were failing, and we had no CI to block us from merging buggy commits to master. Now, all* of that is solved!
* Minor black fixes
* Add Github CI: runs `cookiecutter`, and then within the new project, `make dev-start` and `make ci`.
* Due to all the container overhead in the above steps, CI takes a few minutes to run for every commit/PR.
* Other commands (`make X`), etc.: these should be fairly easy to add by pattern-matching in `ci.yml`.
Closes #56. 
\* This won't catch every bug, but it should get the most egregious ones that break the cookiecutter, the container build, or the default tests.

fix(build): Fix default build and add github CI for cookiecutter

---

{{ cookiecutter.project_name }}/Makefile
{{ cookiecutter.project_name }}/docker/docker-compose.yml

Address minor issues and usability improvements to Makefile.
I'm planning to cut a new release (2.1.0) after this PR: if you think there are other things that need to be addressed before that, please let me know.
* Remove bash container (all CLI entrypoints are run in the jupyter container)
* Improve Makefile readability
* docker-compose file is a Makefile argument so that it's easier to run with different compose files (e.g., a cloud setup with an MLFlow server doesn't need an MLFlow container)
* Small Makefile improvements
* mypy shows error codes (h/t @joegoldbeck)
* isort is now compatible w/black (h/t @resdntalien)
* No more bash container
* N/A: No new tests, but no new testable features
Closes #52.
Closes #53.
Closes #57.

fix(misc): misc fixes to Makefile, and remove bash container

---

.github/workflows/ci.yml
hooks/pre_gen_project.py

When testing locally, I kept running into issues because the version of cookiecutter that I installed through homebrew somehow connected itself to the system python (i.e., `/usr/bin/python`, installed by Mac OS X), which is python 2. This broke the format strings in the pre-generation validation hook.
To minimize user error like mine, this PR keeps the hook compatible with both python2 and python3.
* Validation hook no longer uses Python 3 string formatting syntactic sugar `f"{package_name}"`
* N/A
* N/A: GH actions will test running cookiecutter with python2 and python3.

fix(validation): make validation hook python2 compatible

---

{{ cookiecutter.project_name }}/Makefile
{{ cookiecutter.project_name }}/README.md
{{ cookiecutter.project_name }}/SETUP.md

The current README is a bit obsolete. It also contains two disparate pieces of information: (a) how to get set up with docker, and (b) how to actually run the stuff for the project you create. Since (a) is the same regardless of project, I moved it to a separate `SETUP.md`.
* Split documentation into README/SETUP
* Remove references to bash container
* Style changes to text
* Revert Makefile changes from #61, since I didn't realize the automatic documentation generator relied on that format
* N/A
* N/A
Closes #24.

docs(general): Split readme into readme/setup, and revert makefile changes

---

{{ cookiecutter.project_name }}/Makefile

Require `.env` to exists, and make it if it doesn't
* Add req in makefile
* Add command to build env
* `make dev-start` doesn't fail if you clone an orbyter repo

feat: touch .env if it doesn't exist

---

{{ cookiecutter.project_name }}/docker/docker-compose.yml

I was running into issues running `make dev-start` on a clean cookiecut of the repo: see issue #71. This PR fixes this issue as well as adds additional robustness to the mlflow container
* Escape character in docker compose command: (see https://github.com/docker/compose/issues/4189)
* Allow user to `export` MLflow env vars if they don't like `.env` files
* Should fix #71 
Closes #71 .

fix: make docker compose more robust to env vars

---

{{ cookiecutter.project_name }}/docker/docker-compose.yml

I broke the mlflow container in my last PR. If you pass env vars through `environment:` in the docker compose and they aren't set, docker thinks they are empty even if they are in the `.env`
* remove env vars from mlflow container :(
* mlflow container spins up
I cookiecut this branch and ran `make dev-start`

fix: remove env vars. empties overwrite .env file

---

.github/workflows/ci.yml

We never verify that we aren't making changes that effect the docker containers spinning up. Here, we add a test to check two containers are being spun up
* Add a verify docker container count to CI
* Will fail if two containers don't spin up
Closes #59

feat: add check for 2 spun up docker containers

---

{{ cookiecutter.project_name }}/Makefile

The `make docs` messaged are confusing. They make it difficult to find the docs. This PR clarifies that.
* Echo helpful message

doc: clarify where documentation is

---

cookiecutter.json
{{ cookiecutter.project_name }}/{{ cookiecutter.package_name }}/scripts/train.py

This just changes the default orbyter docker image to `orbyter-ml-dev:3.5`.
* Updated default image to 3.5
* Removed leading and trailing whitespace in docstring in `scripts/train.py` that caused the latest version of `black` to complain

feat: bump docker image version to 3.5

---

.github/workflows/ci.yml

We don't really need 2.7 for this repo

Remove 2.7 test. It fails a library depedency for cookiecutter

---

.github/workflows/ci.yml
README.md
{{ cookiecutter.project_name }}/Makefile

Recreating the fix that we put in place in the newhire_onboard repo to fix the issue where the blank .env file prevents the mlflow container from working correctly
* Updated the Makefile to copy the env_template to the .env file rather than creating a blank .env file if one does not already exist

updating the Makefile to fix the issue with the blank .env file

---

README.md

Updates the README with up-to-date docker cheatsheet link and removes the obsolete kitematic link.

doc: update docker cheatsheet link, remove kitematic link

---

README.md
{{ cookiecutter.project_name }}/README.md

I updated some of the broken links and images in the readme files.
* Updated the links in the `REAMD.md` in the root directory.
* Updated the links and image paths in the `REAMD.md` in the `{{ cookiecutter.project_name }}/README.md` directory.
I did not update all of the links to files within the repository because I'm not sure how you all want to structure those files. Here's what I noticed that needs to be updated:
- `etl.py` script is missing so Step 4 in `{{ cookiecutter.project_name }}` does not work.
- The links for the example configs are broken because there is no longer an example folder. It was changed from `configs/examples/config_example.yml` to `configs/config.yml`. There is a paragraph that says there are multiple example yml files, but there is only one in `configs`. So, …

doc: updated broken links

---

{{ cookiecutter.project_name }}/Makefile

Small fix: the Makefile target `nb` fails if the containers are not running, so I added `dev-start` as a dependency.

feat: make nb now launches containers if they are not spun up
